### ISSUE TITLE
ImportError: No module named 'glacier_upload'

### ISSUE THREAD

**Issue by GaLaKtIkUs** [tbumi/glacier-upload#12]
Installed for git in a virtual environment and git the following error:
```
Traceback (most recent call last):
  File "/opt/backup/glacier-env/bin/glacier_upload", line 11, in <module>
    load_entry_point('glacier-upload==1.1', 'console_scripts', 'glacier_upload')()
  File "/opt/backup/glacier-env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/backup/glacier-env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/opt/backup/glacier-env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/opt/backup/glacier-env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'glacier_upload'
```

Steps to reproduce:
```
virtualenv-3 glacier-env
source glacier-env/bin/activate
pip install --upgrade pip
cd glacier-upload/
python setup.py install
glacier_upload --help
```

**Comment by rom1504** [comment]
getting the same thing when installing with pip...

**Comment by DziubaMaksym** [comment]
getting same error, installed via setup.py install

**Comment by pokey** [comment]
I got the same error with `pip install glacier_upload`.  Was able to get it working by cloning this repo and doing `pip install -e .`

**Comment by rlevitsky** [comment]
I faced the same issue.
To solve: manually copy 'glacier_upload' and 'glacier_upload.egg-info' directories to my 'python3.6/site-packages' directory.
