### ISSUE TITLE
AttributeError: 'module' object has no attribute 'log2'

### ISSUE THREAD

**Issue by henryleparisien** [tbumi/glacier-upload#18]
Hello guys I get an error when I launch an upload  : 
**# glacier_upload -v MYVAULT -f backup.tar** 
_Traceback (most recent call last):
  File "/usr/local/bin/glacier_upload", line 10, in <module>
    sys.exit(upload())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glacier_upload/upload.py", line 54, in upload
    if not math.log2(part_size).is_integer():
AttributeError: 'module' object has no attribute 'log2'_

Looks like a Math module  issue ?
using python 2.7

Thanks in advance

**Comment by avinash-oza** [comment]
Hi,

Based on the readme python2.7 is not supported.
