### ISSUE TITLE
delete_glacier_archive shows TypeError: delete_archive() got an unexpected keyword argument 'upload_id'

### ISSUE THREAD

**Issue by evimed** [tbumi/glacier-upload#22]
Hi !

When I run delete_glacier_archive -v XXXX --upload-id YYYYYZZZZZ
I get the following error:

Traceback (most recent call last):
  File "delete_glacier_archive", line 11, in <module>
    load_entry_point('glacier-upload==1.2', 'console_scripts', 'delete_glacier_archive')()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: delete_archive() got an unexpected keyword argument 'upload_id'

All other utilities of glacier_upload work fine.

Can you help us solve this problem ?
Best,
   Antonio

**Comment by avinash-oza** [comment]
Hey,

I believe the argument should be --archive-id (at least in master as I see)

**Comment by tbumi** [comment]
Sorry for the late response. Yes, the argument should be `--archive-id` instead of `--upload-id`. I hope this answers your question.
