### ISSUE TITLE
botocore.exceptions.NoRegionError: You must specify a region

### ISSUE THREAD

**Issue by deltaidea** [tbumi/glacier-upload#24]
Hi! I'm doing something wrong and I can't figure out what exactly.
Calling `glacier_upload --help` gives me:

```
Traceback (most recent call last):
  File "/usr/local/bin/glacier_upload", line 11, in <module>
    load_entry_point('glacier-upload==1.2', 'console_scripts', 'glacier_upload')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/glacier_upload/upload.py", line 33, in <module>
    glacier = boto3.client('glacier')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 839, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 117, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

Changing the command to `glacier_upload --help --region eu-central-1` results in the same error.

I'm using Amazon Linux 2 (RHEL 7), Python 3.6. Tried both `pip install glacier_upload` and running `python3 setup.py install` in the latest `develop` version. Does this `botocore` mentioned in the stacktrace have the wrong version? I'm not very experienced with Python. ¯\\\_(ツ)_/¯

**Comment by deltaidea** [comment]
Ah, I figured it out. I'm running this utility from inside an EC2 instance where you don't have to run `aws configure`, the credentials are populated automatically. This utility seems to assume the region is also set but it isn't in this case. Solution:

```sh
export AWS_DEFAULT_REGION=eu-central-1

# Now this should work:
glacier_upload --help
```

Ref: https://stackoverflow.com/a/19373803
