### ISSUE TITLE
delete_glacier_archive options error

### ISSUE THREAD

**Issue by sebaswind** [tbumi/glacier-upload#28]
I installed  glacier_upload 1.2 via pip3

When I issue the help option on `delete_glacier_archive` it shows:
```
delete_glacier_archive --help
Usage: delete_glacier_archive [OPTIONS]

Options:
  -v, --vault-name TEXT  The name of the vault  [required]
  -u, --upload-id TEXT   ID of the archive to delete  [required]
  --help                 Show this message and exit.
```
But when try to delete an archive the script fails:

```
delete_glacier_archive --vault-name $VAULT --upload-id $ARCHIVE_ID
Traceback (most recent call last):
  File "/usr/local/bin/delete_glacier_archive", line 8, in <module>
    sys.exit(delete_archive())
  File "/home/sebastian/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sebastian/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sebastian/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: delete_archive() got an unexpected keyword argument 'upload_id'
```
So I searched in the source directory and it shows the `--archive-id` option.
i tried with this new option but fails again:
```
delete_glacier_archive --vault-name $VAULT --archive-id $ARCHIVE_ID
Usage: delete_glacier_archive [OPTIONS]
Try 'delete_glacier_archive --help' for help.

Error: no such option: --archive-id

```
my python knowledge is not good enough to try to fix it or recognize the problem :disappointed:

**Comment by tbumi** [comment]
Hi, [version 2.0](https://pypi.org/project/glacier-upload/2.0/) has this function removed. If you want to delete an archive, please use the [AWS CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/glacier/delete-archive.html).
